title: Alex Schell
description: Personal site and blog
author: Alex Schell
email: schell.alex@gmail.com
url: "https://alexschell.github.io"

markdown: kramdown
permalink: /:year/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
